// Text extracted verbatim from the four approved FastCoat TopCoat specifications.
// Do not rewrite, summarise, or spell-check these strings.

export const FULLY_PRIMED_SURFACES = [
    "Fibre Cement",
    "Concrete",
    "Existing Coatings",
    "Single-Ply",
    "GRP",
    "Metal",
  ];
  
  export const COMMON_BEFORE_ROOF = [
    "Before tendering the contractor should visit site and ascertain all local conditions and restrictions,",
    "accessibility, the full extent and nature of the work, the supply and conditions affecting labour and the",
    "execution of the contract generally, no claims arising from the failure to do so will be considered.",
    "All roofing materials are to be supplied by LRS and to be fit for purpose and of the type and quality",
    "herein. Any sub-standard materials will be rejected. No alternatives are to be substituted.",
    "The contractor shall employ none but LRS Approved, competent tradesman and the whole of the",
    "works shall be carried out and completed in accordance with the correct FastCoat Pro Specification.",
    "Waterproofing Only",
    "This specification is based on a waterproofing only overlay and of an existing roof covering and does",
    "not include thermal insulation.",
    "Measuring the Roof",
    "It is important to accurately measure your roof to determine the amounts of materials required.",
    "(Including a realistic amount for wastage – guide minimum 10% of the gross surface area).",
    "The roof area should include all areas to be coated including upstands and perimeter details etc.",
    "Existing Falls",
    "FastCoat will follow the contours of the existing surface. Falls and any deviations will be replicated.",
    "As a result, some areas of standing water may occur. Please note the accumulation of ice, frost or",
    "ponding water will not have an adverse effect on the FastCoat membrane. However good roofing",
    "practise suggests areas of ponding water should be eliminated.",
    "This applies to the life expectancy and / or the long-term performance of the system and will not",
    "affect the product guarantee in any way.",
    "Change is Scope of Works",
    "LRS must be informed immediately of any proposed requirements to change, and the approved",
    "installer must not implement any changes until agreed by LRS.",
    "LRS will not be responsible for any changes of which they are not aware of or have not authorised,",
    "nor will they accept any liability or associated cost due to system failure.",
    "Existing Roof Condition",
    "The existing roof build-up should be inspected for defects and made good where required.",
    "[[PAGE_GAP]]",
    "Taking core samples of several random areas to obtain information of the sub-structure below the roof",
    "surface is highly recommended. This is the responsibility of the roofing contractor and could help",
    "prevent any unforeseen issues arising during or after application.",
    "Any areas where the insulation or the underlying substrate has collapsed, is defective or decayed,",
    "should be cut out, repaired, and reinstated on a like-for-like basis to provide a good solid base for the",
    "new coating system.",
    "No claims can be considered by Liquid Roofing Systems Ltd should there be any latent defects",
    "resulting from faulty decking or substrate.",
    "Natural Growth/Vegetation",
    "•   Remove all existing vegetation by mechanical extraction.",
    "•   LRS 799 Wash-N-Prep may be used to remove stubborn staining / growth. Consult separate",
    "data sheet for more further information.",
    "•   Wash off any 799 Wash-N-Prep residues before applying any LRS waterproof coatings.",
    "•   1no. 799 Wash-N-Prep 1ltr bottle will clean approx. 148m² at a ratio of 16:1 with clean water.",
    "•   799 Wash N Prep can be added to either a pump sprayer or as an attachment on a power",
    "washer.",
    "•   For general cleaning add 250ml of 799 Wash N Prep to 4ltrs of clean water.",
    "•   For heavy duty cleaning add 500ml of 799 Wash N Prep to 4ltrs of clean water.",
    "•   Once applied the 799 Wash N Prep should be left for a minimum of 15 minutes to allow the",
    "stubborn stains to loosen.",
    "•   The roof should be power washed using clean water to remove any loosened material and",
    "residue.",
    "Adhesion Test",
    "Test Areas:",
    "Clean and remove all dust and contamination before performing test patches. The surface should be",
    "primed using the relevant primer and allowed to dry.",
    "The contractor must document and record the identified test areas after applying the FastCoat",
    "Waterproof.",
    "The FastCoat Waterproof must be allowed to fully cure for 7 Days prior to the adhesion test being",
    "undertaken.",
    "This is to ensure all cleaning and preparation works have been carried out and completed to allow",
    "successful bonding of the liquid system in compliance with manufacturers specifications.",
    "Should the adhesion test fail the contractor must inform LRS immediately upon their findings so that",
    "alternative measures can be agreed before the main works commence.",
    "Compliance with Building Regulations",
    "[[PAGE_GAP]]",
    "You should ensure that the design of the roof to which the FastCoat Pro is to be applied is in",
    "accordance with current regulations, codes and good practice.",
    "For further guidance consult with:",
    "•   BS6229 (Code of Practice for flat roofs with continuously supported coverings).",
    "•   BS5250 (Control of Condensation in Buildings).",
    "•   Local Authority Building Control regarding compliance with regulations or seek professional",
    "advice.",
    "Flat Roof Detailing Guidance",
    "Any redundant roof details should be removed prior to the commencement of works.",
    "The roof area underneath should be made good as required, ensuring that it matches the build-up of",
    "the surrounding roof area.",
    "Termination details should have a minimum 150mm upstand height above the finished surface of the",
    "roof and should be terminated into a chase or have a suitable cover flashing or weathering flange.",
    "Any details that are unable to meet the 150mm should be terminated using a termination bar or LRS",
    "PU mastic.",
    "Any details where this cannot be achieved should be periodically inspected and may require",
    "occasional maintenance.",
    "All detailing surfaces to be coated should be fully prepared and primed as per the main specification.",
    "The Detailing should be dressed as far as possible into all outlets. (Minimum 150mm).",
    "Care should be taken to ensure all roof details comply with:",
    "•   BS 6229 Guidance (Flat Roofs with Continuously Supported Membranes)",
    "•   Guide 7.1 (Flat Roofs and Balconies) of the NHBC Standards 2020",
    "•   Liquid Roofing and Waterproofing Association Design Guide for Liquid Applied",
    "Waterproofing Systems for Roofs and Balconies, Issue 1, 2020",
    "CDM",
    "CDM Regulations are applicable to all construction projects – commercial or domestic.",
    "The Contractor’s responsibilities include:",
    "•   Ensuring that all employed/appointed workers have the skills, knowledge, training, and",
    "experience to carry out the works, or are in the process of obtaining them.",
    "•   Providing appropriate supervision, information, and instructions to workers under their",
    "control.",
    "Operatives should take an active part in helping to manage health and safety risks. Responsibilities",
    "include:",
    "•   Only carrying out construction work if they have the relevant skills, knowledge, training, and",
    "experience. Alternatively, operatives need to ensure that they are provided with the training",
    "and supervision that enables them to do their works safely and without risk to health.",
    "[[PAGE_GAP]]",
    "Safety Precautions",
    "Safety Equipment – Gloves, Goggles, Safety Boots, Hi-Viz and Face Mask – Please refer to",
    "the FastCoat MSDS.",
    "Working from Heights – The Work from Height Regulations 2005",
    "Safe Access - Safe access to a roof requires careful planning, particularly where work",
    "progresses along the roof.",
    "Typical methods to access roofs are:",
    "•   general access scaffolds.",
    "•   stair towers.",
    "•   fixed or mobile scaffold towers.",
    "•   mobile access equipment.",
    "•   ladders; and",
    "•   roof access hatches.",
    "•   Access should be installed and signed off by the appropriate access professional.",
    "Roof edges and openings",
    "Access requirements should meet HSE regulations and guidelines when working at heights.",
    "Fragile surfaces",
    "Always follow a safe system of work using a platform beneath the roof where possible. Work",
    "on or near fragile roof surfaces requires a combination of stagings, guard rails, fall restraint,",
    "fall arrest and safety nets slung beneath and close to the roof.",
    "•   Fragile roofs: all roofs should be treated as fragile until a competent person has confirmed",
    "they are not. Do not trust any sheeted roof, whatever the material, to bear the weight of a",
    "person. This includes the roof ridge and purlins.",
    "•   Fragile rooflights are a particular hazard. Some are difficult to see in certain light",
    "conditions and others may be hidden by paint. You must provide protection in these",
    "areas, either by using barriers or covers that are secured and labelled with a warning.",
    "Electrical Hazards – Be aware of overhead power lines",
    "Protection of landscape Cars and Structures - Ensure all areas are covered that is not part",
    "of the roof works to avoid damage, especially when using chemical cleaners and liquid",
    "waterproofing products.",
    "Handling Chemicals – Control of Substances Hazardous to Health (COSHH)",
    "Regulations 2002.",
    "Temperature Limitations – +5°c to 35°c"
  ];
  
  export const TWENTY_YEAR_AFTER_ROOF = [
    "LRS have been brought in to provide a 20-year product guarantee using FastCoat Pro.",
    "The correct HSE approved access and safety systems should be implemented to ensure a safe working",
    "environment for all employees.",
    "Preparation",
    "Preparing a roof surface before applying FastCoat Waterproof is crucial for ensuring proper adhesion",
    "and longevity of the coating. Here are the steps to prepare a roof surface effectively:",
    "1.      Inspection",
    "• Inspect the Roof: Look for any damage, such as cracks, blisters, or punctures. Note areas",
    "that require repair.",
    "• Check for Moisture: Ensure the roof is completely dry. Moisture trapped under the",
    "coating can cause bubbling and poor adhesion.",
    "• LRS recommend carrying out core samples to determine the condition of the existing",
    "build up.",
    "2.      Cleaning",
    "Please see page 12.",
    "3.      Repairing",
    "• Repair Damage: Fix any cracks, blisters, or punctures. Use appropriate materials such as",
    "LRS PU Mastic for minor repairs.",
    "• Seal Joints and Seams: Use LRS PU Mastic to ensure all joints and seams are watertight.",
    "• Replace Damaged Sections: If parts of the roofing material are severely damaged, they",
    "should be replaced like for like.",
    "4. Final Preparations",
    "• Masking: Protect areas that should not be coated using masking tape and protective",
    "coverings.",
    "• Mixing the Coating: Mix the FastCoat Waterproof thoroughly before application.",
    "5.      Safety Measures – Please see page 9-10.",
    "Cleaning",
    "Objective: Ensure the roof surface is properly prepared for the application of FastCoat Pro",
    "Waterproof to achieve optimal adhesion and performance.",
    "Safety Precautions: Please see pages 9-10.",
    "Cleaning Steps:",
    "[[PAGE_GAP]]",
    "1. Clear Debris:",
    "• Use a broom or leaf blower to remove loose debris such as leaves, twigs, and dirt.",
    "• Check for and remove any nesting materials or other obstructions.",
    "2. Pressure Washing:",
    "• Use a 2000 psi pressure washer to thoroughly wash the roof. Start at the furthest point and",
    "work your way to your exit point",
    "799 Wash N Prep",
    "3. Apply 799 Wash N Prep if required:",
    "• Mix 799 Wash N Prep at a ratio of 16:1 for general cleaning. 1 part 799 Wash N Prep and",
    "16 parts clean water.",
    "• Apply the 799 Wash N Prep to the roof using a pump sprayer or stiff-bristle brush. Allow",
    "to sit for 15-20 minutes before rinsing away with clean water.",
    "• For stubborn stains, mix 1 part 799 Wash N Prep with 8 parts clean water and apply it to",
    "the affected areas. Let it sit for 15-20 minutes before rinsing with clean water.",
    "4. Rinse Thoroughly:",
    "• Rinse the roof thoroughly with clean water to remove all soap and cleaning solution",
    "residues.",
    "• Ensure no cleaner is left behind as it can affect the adhesion of FastCoat Waterproof.",
    "5. Inspect and Repair:",
    "• Inspect the roof for any damage, such as cracks, splits, or holes. Repair minor issues with",
    "LRS PU Mastic.",
    "• Ensure the roof surface is smooth and intact.",
    "6. Drying:",
    "• Allow the roof to dry completely before applying the waterproof coatings. This may take",
    "several hours to a full day, depending on weather conditions.",
    "Final Steps:",
    "•    Documentation: Take photos before and after cleaning to document the condition of the roof.",
    "TV Aerials and Satellite Dish Arrays",
    "Any TV aerials or satellite arrays that will impede the roofing works will need to be temporarily",
    "removed or raised to facilitate the works.",
    "The contractor must liaise with the client directly in relation to how to best serve the property so that",
    "minimal disturbance of service is achieved throughout the roof works.",
    "Cables",
    "If a cable tray is not currently in situ, then consideration should be made to keep the cables from",
    "direct contact with the membrane.",
    "[[PAGE_GAP]]",
    "Waterproofing Coverings",
    "Existing Details, Terminations and Upstands:",
    "To ensure a durable and effective waterproofing system for a flat roof using FastCoat, it is essential to",
    "properly handle existing details, terminations, and upstands.",
    "Steps for Existing Details, Terminations, and Upstands:",
    "1. Safety First – Please see pages 9-10.",
    "2. Preparation of Existing Details",
    "Please see page 11.",
    "3. Ensuring Proper Height for Upstands",
    "[[PAGE_GAP]]",
    "o Upstands should be a minimum of 150mm where possible high to prevent water",
    "ingress.",
    "o Measure the height and adjust if necessary to meet this requirement.",
    "4. Applying FastCoat Waterproof Coating",
    "Please see page 16.",
    "5. Terminating the Waterproofing System",
    "o There are four main methods to finishing the FastCoat Waterproof system: Leaving",
    "the membrane self-terminated, using a termination bar, lead flashing, or cutting into a",
    "chase filled with LRS PU Mastic.",
    "Method 1: Self-terminating",
    "•   Mark the termination height of 150mm using a string line or masking tape.",
    "•   Apply the FastCoat Waterproof to specification up to the termination line.",
    "•   Ensure the FastCoat is fully bonded to the upstand leaving no voids or gaps",
    "which could allow water ingress.",
    "•   Terminating the FastCoat is best practise, please see below other options.",
    "Method 2: Using a Termination Bar",
    "•   Measure and Cut: Measure and cut the termination bar to fit the length of the upstand.",
    "•   Position the Bar: Position the termination bar at the top edge of the waterproof coating,",
    "ensuring it is at least 150mm above the roof surface.",
    "•   Fasten the Bar: Secure the termination bar to the wall using suitable fixings.",
    "•   Seal with LRS PU Mastic: Apply LRS PU Mastic along the top edge of the termination bar to",
    "seal it.",
    "Method 3: Using Lead Flashing",
    "•   Measure and Cut: Measure and cut the lead flashing to fit the length of the upstand.",
    "•   Install Flashing: Install the lead flashing at the top edge of the FastCoat waterproof coating,",
    "ensuring it covers the termination of the coating.",
    "•   Secure Flashing: Secure the lead flashing into the brickwork or wall by cutting a chase.",
    "•   Seal with LRS PU Mastic: Apply LRS PU Mastic along the edges of the lead flashing and",
    "into the chase to seal it.",
    "Method 4: Cutting into a Chase and Filling with LRS PU Mastic",
    "•   Cut a Chase: Use a grinder or chisel to cut a chase (groove) into the wall at the top edge of the",
    "waterproof coating, at least 150mm above the roof surface.",
    "•   Clean the Chase: Clean out the chase to remove dust and debris.",
    "•   Waterproof: Apply FastCoat Waterproof into the chase to the correct FastCoat Specification.",
    "•   Fill with LRS PU Mastic: Embed the top edge of the waterproof coating into the chase. Once",
    "dry, Fill the chase with LRS PU Mastic.",
    "[[PAGE_GAP]]",
    "6. Final Inspection",
    "o Inspect all terminations and upstands to ensure they are properly sealed and finished.",
    "o Check for any gaps or unsealed areas and repair where necessary.",
    "FastCoat Waterproof as a Base Coat:",
    "Applying FastCoat Waterproof with Reinforcement Matting ensures a robust and durable",
    "waterproofing system for your flat roof.",
    "Steps for Applying FastCoat Waterproof and Reinforcement Matting:",
    "1. Safety First – Please see pages 9-10.",
    "2. Surface Preparation",
    "o Ensure the surface is clean, dry, and free from dust, debris, and grease.",
    "o Follow the cleaning and priming steps outlined previously if necessary.",
    "3. Mixing FastCoat Waterproof",
    "o Thoroughly mix the FastCoat Waterproof prior to application. Use a drill and mixing",
    "attachment or mixing stick to ensure uniform consistency.",
    "4. Measure and Cut Reinforcement Matting",
    "o Measure the roof area and cut the Reinforcement Matting to size.",
    "o Ensure edges are overlapped by approx. 50mm using the furry edge.",
    "5. Application of FastCoat Waterproof",
    "o First Section: Start with a manageable section of the roof.",
    "o Coverage Rate: Apply the FastCoat Waterproof at a coverage rate of 1.5kg per m².",
    "Use a short pile roller or brush for even application.",
    "o Embed Reinforcement Matting: While the FastCoat Waterproof is still wet, embed",
    "the Reinforcement Matting into the FastCoat Waterproof. Ensure it lies flat and",
    "smooth without wrinkles or air bubbles.",
    "o Overlap Matting: Overlap adjacent pieces of Reinforcement Matting by 50mm to",
    "ensure a continuous and strong layer.",
    "6. Embedment",
    "o Use the roller to press the Reinforcement Matting firmly into the FastCoat",
    "Waterproof, ensuring good saturation and adhesion.",
    "o Apply additional FastCoat Waterproof on top of the matting at a coverage rate of",
    "0.5kg per m² to ensure it is fully saturated and covered. Once the Reinforcement",
    "Matting has broken down and is soft ensure the embedment is carried out to remove",
    "all pinholes.",
    "7. Repeat Process",
    "o Move to the next section of roof and repeat the application process, ensuring each",
    "piece of matting overlaps the previous one by 50mm.",
    "[[PAGE_GAP]]",
    "8. Drying Time",
    "o Allow the FastCoat Waterproof and Reinforcement Matting to dry, typically 2-4 hours",
    "before applying any topcoats or additional layers.",
    "9. Clean Up",
    "o Clean tools and equipment.",
    "o Dispose of any leftover materials and containers according to local regulations.",
    "FastCoat Waterproof as a BaseCoat:",
    "Single component, moisture curing polyurethane.",
    "Container Size – 25kg",
    "Coverage Rates (Typical)",
    "2kg / m² (Smooth Surface) – 12.5m² / 25kg tin",
    "2.25kg / m² (Rough Surface) – 11.1m² / 25kg tin",
    "Allowance should be made for additional coverage rates for embedment of the Reinforcement Matting",
    "at low temperatures.",
    "Typical Drying Times at 15°c",
    "Touch Dry – 3 hours",
    "Minimum Over Coat – 4 hours",
    "Full Cure – 7 days",
    "Storage",
    "FastCoat should be stored between 5°c and 20°c and kept out of the weather elements.",
    "Application Temperatures",
    "FastCoat is based on surface temperature and should be applied between +5°c and the maximum",
    "surface temperature is 35°c.",
    "FastCoat BaseCoat – Inspect",
    "Inspecting the FastCoat Waterproof is a crucial step to ensure there are no imperfections such as",
    "pinholes or wicks that could compromise the waterproofing system.",
    "Steps for Inspecting and Repairing FastCoat Waterproof:",
    "1. Safety First – Please see pages 9-10.",
    "2. Initial Inspection",
    "o Visual Check: Begin with a visual inspection of the entire roof surface. Look for any",
    "visible defects such as pinholes, air bubbles, or wicks.",
    "o Lighting: Use a flashlight or inspection light to illuminate the surface. This helps in",
    "identifying small pinholes and imperfections that may not be visible under normal",
    "lighting conditions.",
    "[[PAGE_GAP]]",
    "3. Identifying Pinholes",
    "o Mark Pinholes: As you identify pinholes, mark them with a marker or chalk to ensure",
    "they are easy to locate during the repair process.",
    "o Check All Areas: Ensure you check all areas, including edges, corners, and around",
    "details where Reinforcement Matting has been used.",
    "4. Repairing Pinholes",
    "o Clean Area: Clean the area around the pinholes to ensure it is free from dust and",
    "debris.",
    "o Apply LRS PU Mastic: Use a sealant gun to apply LRS PU Mastic into the pinholes.",
    "Ensure the mastic fills the hole completely.",
    "o Smooth Surface: Smooth the LRS PU Mastic to ensure a level surface.",
    "5. Dealing with Wicks or Fibres",
    "o Sand Wicks: Lightly sand any wicks or fibres standing proud using 80 grit sandpaper.",
    "Sand gently to avoid damaging the surrounding FastCoat Waterproof.",
    "o Clean Surface: Wipe the sanded area with a clean cloth to remove dust.",
    "6. Ensuring Full Coverage",
    "o Check Coverage: Ensure the entire roof area is coated with the FastCoat Waterproof",
    "and that Reinforcement Matting is properly embedded.",
    "o Inspect Matting: Verify that all Reinforcement Matting is in place, fully saturated,",
    "and overlaps are correctly done by at least 50mm.",
    "7. Detail Inspection",
    "o Details and Edges: Pay attention to details and edges. Ensure all areas with",
    "Reinforcement Matting are thoroughly inspected and properly coated.",
    "o Completed Details: Check that all details, such as terminations and upstands, are",
    "completed with Reinforcement Matting and properly coated.",
    "8. Final Inspection",
    "o Comprehensive Check: Perform a final comprehensive check of the entire roof area.",
    "Look for any missed spots or areas that may need additional attention.",
    "o Repair as Needed: Address any remaining issues with LRS PU Mastic and ensure all",
    "repairs are smooth and level before recoating.",
    "FastCoat Waterproof as a TopCoat:",
    "Applying the FastCoat Waterproof is a critical final step in creating a durable and watertight flat roof.",
    "Steps for Applying FastCoat TopCoat:",
    "[[PAGE_GAP]]",
    "1. Safety First – Please see pages 9-10.",
    "2. Inspect the BaseCoat",
    "o Check for Pinholes: Ensure all pinholes have been filled and the surface is smooth.",
    "o Clean Surface: Make sure the surface is clean and free from dust and debris. See page",
    "14",
    "3. Reactivation of the Surface (if required)",
    "o If the BaseCoat has been left for more than 14 days, you must reactivate the surface",
    "using MS 2-Part Primer.",
    "o Apply Primer: Apply the MS 2-Part Primer as per LRS instructions and allow it to",
    "dry completely before applying the FastCoat Waterproof.",
    "4. Mixing the FastCoat TopCoat",
    "o Thoroughly mix the FastCoat TopCoat before application. Use a drill with mixing",
    "attachment or mixing stick to ensure uniform consistency.",
    "5. Application of FastCoat TopCoat",
    "o Coverage Rate: Apply the FastCoat TopCoat at a coverage rate of 0.3kg per m².",
    "o Even Application: Use a short pile roller or brush to apply the FastCoat TopCoat",
    "evenly. Ensure consistent thickness and avoid leaving streaks or thin spots.",
    "o Consistent Strokes: Apply the FastCoat TopCoat in consistent, straight strokes to",
    "achieve an even finish.",
    "6. Drying Time",
    "o Allow the FastCoat TopCoat to dry for 2-4 hours, depending on environmental",
    "conditions such as temperature and humidity.",
    "7. Final Inspection",
    "o Even Coverage: Check the roof to ensure the FastCoat TopCoat has been applied",
    "evenly across the entire surface.",
    "o Touch-ups: Perform any necessary touch-ups with additional FastCoat TopCoat to",
    "cover missed spots or thin areas.",
    "FastCoat TopCoat:",
    "Single component Polyurethane, Solvent Based Aliphatic Coloured TopCoat.",
    "Container Size – 5.5kg",
    "Coverage Rates (Typical)",
    "0.3kg / m² (Smooth Surface) – 18.3m² / 5.5kg tin",
    "Typical Drying Times at 15°c",
    "Touch Dry – 3 hours",
    "Minimum Over Coat – 4 hours",
    "[[PAGE_GAP]]",
    "Full Cure – 7 days",
    "Storage",
    "FastCoat should be stored between 5°c and 20°c and kept out of the weather elements.",
    "Application Temperatures",
    "FastCoat is based on surface temperature and should be applied between +5°c and the maximum",
    "surface temperature is 35°c.",
    "Completed Roof Surface",
    "Guide to Visual Inspection of the Completed Roof Surface",
    "Objective: Conduct a thorough visual inspection of the completed roof surface to ensure there are no",
    "pinholes, the coverage is even, details are correctly applied at 150mm, and Reinforcement Matting is",
    "properly installed over the entire roof area.",
    "Safety Precautions: Please see pages 9-10.",
    "Steps for Visual Inspection:",
    "•   Initial Overview:",
    "o Walk around the perimeter of the roof to get an initial overview of the surface.",
    "o Take note of any obvious defects or areas that require closer inspection.",
    "•   Check for Pinholes:",
    "o Visual Scan: Perform a visual scan of the entire roof surface. Look closely for pinholes.",
    "o Detailed Areas: Pay extra attention to seams, edges, and details where pinholes are more",
    "likely to occur.",
    "•   Ensure Even Coverage:",
    "o Uniform Thickness: Verify that the FastCoat Waterproof is consistent across the entire",
    "roof. There should be no thin spots or exposed substrate.",
    "o Edges and Corners: Check edges, corners, and transitions to ensure they are fully coated",
    "and have no exposed areas.",
    "o Colour Consistency: Look for colour consistency across the surface, as variations can",
    "indicate uneven application.",
    "•   Inspect Details at 150mm:",
    "o Measure Height: Use a measuring tape to check that details such as terminations,",
    "upstands, and other critical points are coated to a minimum height of 150mm where",
    "possible.",
    "o Detail Work: Ensure all details are properly sealed and the FastCoat Waterproof is applied",
    "consistently at the required height.",
    "•   Verify Reinforcement Matting:",
    "o Visible Matting: Inspect areas where Reinforcement Matting was applied. The",
    "Reinforcement Matting should be fully embedded in the coating with no exposed edges.",
    "o Coverage: Ensure the Reinforcement Matting extends to cover all critical areas, such as",
    "joints, seams, and around roof penetrations.",
    "[[PAGE_GAP]]",
    "o   Bonding: Check that the Reinforcement Matting is well-bonded to the substrate and there",
    "are no air pockets or wrinkles.",
    "•   Final Checks:",
    "o Seams and Joints: Verify that all seams and joints are fully sealed and there are no gaps or",
    "openings.",
    "o Overall Condition: Assess the overall condition of the roof surface. Ensure it looks",
    "uniform and well-maintained.",
    "•   Document Findings:",
    "o Photographic Evidence: Take photos of the roof surface, especially any areas of concern",
    "or interest. Capture before and after images if any touch-up work is required.",
    "o Detailed Notes: Write detailed notes on your findings, including any defects, areas that",
    "need additional work, and the overall condition of the roof.",
    "Addressing Issues:",
    "•   Pinholes: Mark any pinholes with chalk or tape. Prepare a small amount of LRS PU Mastic to",
    "fill in the pinholes before reapplying FastCoat Waterproof.",
    "•   Uneven Coverage: Apply additional FastCoat to any areas with insufficient coverage to",
    "achieve uniform thickness.",
    "•   Detail Adjustments: Correct any issues with details that are not at the required 150mm height",
    "where possible. Apply additional coating if necessary.",
    "•   Reinforcement Matting: Ensure any improperly applied Reinforcement Matting is corrected",
    "by applying additional FastCoat Waterproof and embedding new Reinforcement Matting as",
    "needed.",
    "[[TRAFFIC_START]]",
    "Traffic Coat Previsions for walkways, maintenance routes etc.:",
    "Once the LRS FastCoat Waterproof has fully cured, Traffic Coat can be applied.",
    "LRS Traffic Coat is applied in 2 coats (Holding Layer & Seal Coat) and typically cures in 30",
    "mins.",
    "Holding Layer is applied @ 0.2kg m² and while Traffic Coat is still wet immediately",
    "broadcast to saturation, completely blinding the surface with 3kg m² of Emery Aggregate.",
    "Once the Base Layer has fully cured, typically in 30 minutes, the contractor will need to brush",
    "and bag up all the loose aggregate before applying the Seal Coat.",
    "Seal Coat is applied at 0.2kg m² ensuring the aggregate is encapsulated.",
    "Ensure all masking tape is removed once the walkway is complete and the Seal Coat is still",
    "wet to leave a crisp edge.",
    "[[TRAFFIC_END]]",
    "TAKE IMAGES OF EACH STEP OF THE ABOVE IF APPLYING FOR A PRODUCT",
    "GUARANTEE",
    "[[PAGE_GAP]]",
    "General Guidance and Requirements",
    "Drying Out – Equipment:",
    "These are readily available commercially from local tool plant hire companies.",
    "Leaf Blowers",
    "Hot Air Blower",
    "Roof Pumps",
    "Defects:",
    "This specification provided by LRS is written on the basis that the substrates, roof deck and structures",
    "are sound and suitable. We cannot accept responsibility for the consequences of defects in the roof",
    "deck or structure.",
    "Installation:",
    "All LRS Waterproofing Systems are to be installed in accordance with this specification.",
    "Building Works:",
    "It is the contractor’s responsibility to ensure suitable protection of semi-completed or completed",
    "works.",
    "Protection of Works:",
    "It is the contractor’s responsibility to ensure any relating plant, equipment or materials being stored or",
    "placed onto the waterproofing membrane are sufficiently protected.",
    "Delays:",
    "All or general areas: Overcoating must be carried out within 14 days of the application of the",
    "preceding coat (Primer or Waterproofing).",
    "Coatings that are over 14 days will need to be re-activated using LRS MS 2-Part Primer at a coverage",
    "of 0.2kg per m².",
    "[[PAGE_GAP]]",
    "General Guidance - requirements",
    "Prepared Surfaces – Requirement:",
    "Prepared surfaces and substrates to receive the new FastCoat Pro Waterproofing Membrane must be",
    "prepared all in accordance with this specification and must be clean from all dirt, dust and loose",
    "materials. In addition, all surfaces must be dry before application.",
    "Storage:",
    "All LRS materials must always be stored indoors between 5°c and 20°c.",
    "Note: Coverage rates are adversely affected by high and low application temperatures.",
    "Safe Working:",
    "All works are to be carried out in accordance with the current Health and Safety Legislation. Please",
    "see pages 9-10.",
    "Inclement Weather Protection:",
    "If rain is due no LRS Waterproofing coatings should be laid.",
    "The contractor must ensure at the end of each day that any exposed membranes or substrates that are",
    "susceptible to damage through water ingress are sealed and protected to ensure complete water",
    "tightness.",
    "[[PAGE_GAP]]",
    "Maintenance After Installation",
    "The new roof coverings should be managed in accordance with the recommendations of BS6229:2003",
    "with regards to ongoing maintenance.",
    "They should be routinely inspected and cleared of any debris every spring and autumn. This will need",
    "to be undertaken more often if the roof is surrounded by trees etc.",
    "Please note that failure to follow maintenance guidelines can invalidate the product guarantee.",
    "Guarantee – Materials Only",
    "Materials only. The following guarantee specification is covered by LRS product guarantee for the",
    "period of 20-years from the date of practical completion.",
    "Please Note: Only Waterproofing products supplied by LRS will be covered in this guarantee."
  ];
  
  export const TWENTY_FIVE_YEAR_AFTER_ROOF = [
    "LRS have been brought in to provide a 25-year product guarantee using FastCoat Pro.",
    "The correct HSE approved access and safety systems should be implemented to",
    "ensure a safe working environment for all employees.",
    "Preparation",
    "Preparing a roof surface before applying FastCoat Waterproof is crucial for ensuring",
    "proper adhesion and longevity of the coating. Here are the steps to prepare a roof",
    "surface effectively:",
    "1.      Inspection",
    "• Inspect the Roof: Look for any damage, such as cracks, blisters, or",
    "punctures. Note areas that require repair.",
    "• Check for Moisture: Ensure the roof is completely dry. Moisture trapped",
    "under the coating can cause bubbling and poor adhesion.",
    "• LRS recommend carrying out core samples to determine the condition of",
    "the existing build up.",
    "2.      Cleaning",
    "Please see page 12.",
    "3.      Repairing",
    "• Repair Damage: Fix any cracks, blisters, or punctures. Use appropriate",
    "materials such as LRS PU Mastic for minor repairs.",
    "• Seal Joints and Seams: Use LRS PU Mastic to ensure all joints and seams are",
    "watertight.",
    "• Replace Damaged Sections: If parts of the roofing material are severely",
    "damaged, they should be replaced like for like.",
    "4. Final Preparations",
    "• Masking: Protect areas that should not be coated using masking tape and",
    "protective coverings.",
    "• Mixing the Coating: Mix the FastCoat Waterproof thoroughly before",
    "application.",
    "5.      Safety Measures – Please see page 9-10.",
    "Cleaning",
    "[[PAGE_GAP]]",
    "Objective: Ensure the roof surface is properly prepared for the application of",
    "FastCoat Pro Waterproof to achieve optimal adhesion and performance.",
    "Safety Precautions: Please see pages 9-10.",
    "Cleaning Steps:",
    "1. Clear Debris:",
    "• Use a broom or leaf blower to remove loose debris such as leaves, twigs,",
    "and dirt.",
    "• Check for and remove any nesting materials or other obstructions.",
    "2. Pressure Washing:",
    "• Use a 2000 psi pressure washer to thoroughly wash the roof. Start at the",
    "furthest point and work your way to your exit point",
    "799 Wash N Prep",
    "3. Apply 799 Wash N Prep if required:",
    "• Mix 799 Wash N Prep at a ratio of 16:1 for general cleaning. 1 part 799 Wash",
    "N Prep and 16 parts clean water.",
    "• Apply the 799 Wash N Prep to the roof using a pump sprayer or stiff-bristle",
    "brush. Allow to sit for 15-20 minutes before rinsing away with clean water.",
    "• For stubborn stains, mix 1 part 799 Wash N Prep with 8 parts clean water",
    "and apply it to the affected areas. Let it sit for 15-20 minutes before rinsing",
    "with clean water.",
    "4. Rinse Thoroughly:",
    "• Rinse the roof thoroughly with clean water to remove all soap and cleaning",
    "solution residues.",
    "• Ensure no cleaner is left behind as it can affect the adhesion of FastCoat",
    "Waterproof.",
    "5. Inspect and Repair:",
    "• Inspect the roof for any damage, such as cracks, splits, or holes. Repair",
    "minor issues with LRS PU Mastic.",
    "• Ensure the roof surface is smooth and intact.",
    "6. Drying:",
    "• Allow the roof to dry completely before applying the waterproof coatings.",
    "This may take several hours to a full day, depending on weather",
    "conditions.",
    "Final Steps:",
    "•   Documentation: Take photos before and after cleaning to document the",
    "condition of the roof.",
    "[[PAGE_GAP]]",
    "TV Aerials and Satellite Dish Arrays",
    "Any TV aerials or satellite arrays that will impede the roofing works will need to be",
    "temporarily removed or raised to facilitate the works.",
    "The contractor must liaise with the client directly in relation to how to best serve the",
    "property so that minimal disturbance of service is achieved throughout the roof",
    "works.",
    "Cables",
    "If a cable tray is not currently in situ, then consideration should be made to keep the",
    "cables from direct contact with the membrane.",
    "[[PAGE_GAP]]",
    "Waterproofing Coverings",
    "Existing Details, Terminations and Upstands:",
    "To ensure a durable and effective waterproofing system for a flat roof using FastCoat,",
    "it is essential to properly handle existing details, terminations, and upstands.",
    "Steps for Existing Details, Terminations, and Upstands:",
    "1. Safety First – Please see pages 9-10.",
    "2. Preparation of Existing Details",
    "Please see page 11.",
    "3. Ensuring Proper Height for Upstands",
    "o Upstands should be a minimum of 150mm high where possible to",
    "prevent water ingress.",
    "o Measure the height and adjust if necessary to meet this requirement.",
    "4. Applying FastCoat Waterproof Coating",
    "Please see page 16.",
    "5. Terminating the Waterproofing System",
    "o There are four main methods to finishing the FastCoat Waterproof",
    "system: Leaving the membrane self-terminated, using a termination",
    "bar, lead flashing, or cutting into a chase filled with LRS PU Mastic.",
    "Method 1: Self-terminating",
    "•   Mark the termination height of 150mm using a string line or",
    "masking tape.",
    "•   Apply the FastCoat Waterproof to specification up to the termination",
    "line.",
    "•   Ensure the FastCoat is fully bonded to the upstand leaving no voids",
    "or gaps which could allow water ingress.",
    "•   Terminating the FastCoat is best practise, please see below other",
    "options.",
    "[[PAGE_GAP]]",
    "Method 2: Using a Termination Bar",
    "•   Measure and Cut: Measure and cut the termination bar to fit the length of the",
    "upstand.",
    "•   Position the Bar: Position the termination bar at the top edge of the waterproof",
    "coating, ensuring it is at least 150mm above the roof surface.",
    "•   Fasten the Bar: Secure the termination bar to the wall using suitable fixings.",
    "•   Seal with LRS PU Mastic: Apply LRS PU Mastic along the top edge of the",
    "termination bar to seal it.",
    "Method 3: Using Lead Flashing",
    "•   Measure and Cut: Measure and cut the lead flashing to fit the length of the",
    "upstand.",
    "•   Install Flashing: Install the lead flashing at the top edge of the FastCoat",
    "waterproof coating, ensuring it covers the termination of the coating.",
    "•   Secure Flashing: Secure the lead flashing into the brickwork or wall by cutting",
    "a chase.",
    "•   Seal with LRS PU Mastic: Apply LRS PU Mastic along the edges of the lead",
    "flashing and into the chase to seal it.",
    "Method 4: Cutting into a Chase and Filling with LRS PU Mastic",
    "•   Cut a Chase: Use a grinder or chisel to cut a chase (groove) into the wall at the",
    "top edge of the waterproof coating, at least 150mm above the roof surface.",
    "•   Clean the Chase: Clean out the chase to remove dust and debris.",
    "•   Waterproof: Apply FastCoat Waterproof into the chase to the correct FastCoat",
    "Specification.",
    "•   Fill with LRS PU Mastic: Embed the top edge of the waterproof coating into the",
    "chase. Once dry, Fill the chase with LRS PU Mastic.",
    "6. Final Inspection",
    "o Inspect all terminations and upstands to ensure they are properly",
    "sealed and finished.",
    "o Check for any gaps or unsealed areas and repair where necessary.",
    "[[PAGE_GAP]]",
    "FastCoat Waterproof as a Base Coat:",
    "Applying FastCoat Waterproof with Reinforcement Matting ensures a robust and",
    "durable waterproofing system for your flat roof.",
    "Steps for Applying FastCoat Waterproof and Reinforcement Matting:",
    "1. Safety First – Please see pages 9-10.",
    "2. Surface Preparation",
    "o Ensure the surface is clean, dry, and free from dust, debris, and grease.",
    "o Follow the cleaning and priming steps outlined previously if necessary.",
    "3. Mixing FastCoat Waterproof",
    "o Thoroughly mix the FastCoat Waterproof prior to application. Use a drill",
    "and mixing attachment or mixing stick to ensure uniform consistency.",
    "4. Measure and Cut Reinforcement Matting",
    "o Measure the roof area and cut the Reinforcement Matting to size.",
    "o Ensure edges are overlapped by approx. 50mm using the furry edge.",
    "5. Application of FastCoat Waterproof",
    "o First Section: Start with a manageable section of the roof.",
    "o Coverage Rate: Apply the FastCoat Waterproof at a coverage rate of",
    "1.5kg per m². Use a short pile roller or brush for even application.",
    "o Embed Reinforcement Matting: While the FastCoat Waterproof is still",
    "wet, embed the Reinforcement Matting into the FastCoat Waterproof.",
    "Ensure it lies flat and smooth without pinholes, wrinkles or air bubbles.",
    "o Overlap Matting: Overlap adjacent pieces of Reinforcement Matting by",
    "50mm to ensure a continuous and strong layer.",
    "6. Repeat Process",
    "o Move to the next section of roof and repeat the application process,",
    "ensuring each piece of matting overlaps the previous one by 50mm.",
    "7. Drying Time",
    "o Allow the FastCoat Waterproof and Reinforcement Matting to dry,",
    "typically 2-4 hours before applying any topcoats or additional layers.",
    "8. Clean Up",
    "o Clean tools and equipment.",
    "o Dispose of any leftover materials and containers according to local",
    "regulations.",
    "[[PAGE_GAP]]",
    "FastCoat Waterproof as a BaseCoat:",
    "Single component, moisture curing polyurethane.",
    "Container Size – 25kg",
    "Coverage Rates (Typical)",
    "2kg / m² (Smooth Surface) – 12.5m² / 25kg tin",
    "2.2kg / m² (Rough Surface) – 11.1m² / 25kg tin",
    "Allowance should be made for additional coverage rates for embedment of the",
    "Reinforcement Matting at low temperatures.",
    "Typical Drying Times at 15°c",
    "Touch Dry – 3 hours",
    "Minimum Over Coat – 4 hours",
    "Full Cure – 7 days",
    "Storage",
    "FastCoat should be stored between 5°c and 20°c and kept out of the weather elements.",
    "Application Temperatures",
    "FastCoat is based on surface temperature and should be applied between +5°c and the",
    "maximum surface temperature is 35°c.",
    "FastCoat BaseCoat – Inspect",
    "Inspecting the FastCoat Waterproof is a crucial step to ensure there are no",
    "imperfections such as pinholes or wicks that could compromise the waterproofing",
    "system.",
    "Steps for Inspecting and Repairing FastCoat Waterproof:",
    "1. Safety First – Please see pages 9-10.",
    "[[PAGE_GAP]]",
    "2. Initial Inspection",
    "o Visual Check: Begin with a visual inspection of the entire roof surface.",
    "Look for any visible defects such as pinholes, air bubbles, or wicks.",
    "o Lighting: Use a flashlight or inspection light to illuminate the surface.",
    "This helps in identifying small pinholes and imperfections that may not",
    "be visible under normal lighting conditions.",
    "3. Identifying Pinholes",
    "o Mark Pinholes: As you identify pinholes, mark them with a marker or",
    "chalk to ensure they are easy to locate during the repair process.",
    "o Check All Areas: Ensure you check all areas, including edges, corners,",
    "and around details where Reinforcement Matting has been used.",
    "4. Repairing Pinholes",
    "o Clean Area: Clean the area around the pinholes to ensure it is free from",
    "dust and debris.",
    "o Apply LRS PU Mastic: Use a sealant gun to apply LRS PU Mastic into the",
    "pinholes. Ensure the mastic fills the hole completely.",
    "o Smooth Surface: Smooth the LRS PU Mastic to ensure a level surface.",
    "5. Dealing with Wicks or Fibres",
    "o Sand Wicks: Lightly sand any wicks or fibres standing proud using 80",
    "grit sandpaper. Sand gently to avoid damaging the surrounding",
    "FastCoat Waterproof.",
    "o Clean Surface: Wipe the sanded area with a clean cloth to remove dust.",
    "6. Ensuring Full Coverage",
    "o Check Coverage: Ensure the entire roof area is coated with the FastCoat",
    "Waterproof and that Reinforcement Matting is properly embedded.",
    "o Inspect Matting: Verify that all Reinforcement Matting is in place, fully",
    "saturated, and overlaps are correctly done by at least 50mm.",
    "7. Detail Inspection",
    "o Details and Edges: Pay attention to details and edges. Ensure all areas",
    "with Reinforcement Matting are thoroughly inspected and properly",
    "coated.",
    "o Completed Details: Check that all details, such as terminations and",
    "upstands, are completed with Reinforcement Matting and properly",
    "coated.",
    "8. Final Inspection",
    "o Comprehensive Check: Perform a final comprehensive check of the",
    "entire roof area. Look for any missed spots or areas that may need",
    "additional attention.",
    "o Repair as Needed: Address any remaining issues with LRS PU Mastic",
    "and ensure all repairs are smooth and level before recoating.",
    "[[PAGE_GAP]]",
    "FastCoat MidCoat:",
    "Steps for Applying FastCoat MidCoat:",
    "1. Safety First – Please see pages 9-10.",
    "2. Inspect the BaseCoat",
    "o Check for Pinholes: Ensure all pinholes have been filled and the surface",
    "is smooth.",
    "o Clean Surface: Make sure the surface is clean and free from dust and",
    "debris. See page 14",
    "3. Reactivation of the Surface (if required)",
    "o If the BaseCoat has been left for more than 14 days, you must reactivate",
    "the surface using MS 2-Part Primer.",
    "o Apply Primer: Apply the MS 2-Part Primer as per LRS instructions and",
    "allow it to dry completely before applying the FastCoat Waterproof.",
    "4. Mixing the FastCoat MidCoat",
    "o Thoroughly mix the FastCoat Waterproof before application. Use a drill",
    "with mixing attachment or mixing stick to ensure uniform consistency.",
    "5. Application of FastCoat MidCoat",
    "o Coverage Rate: Apply the FastCoat Waterproof at a coverage rate of 1kg",
    "per m².",
    "o Even Application: Use a short pile roller or brush to apply the FastCoat",
    "Waterproof evenly. Ensure consistent thickness and avoid leaving",
    "streaks or thin spots.",
    "o Consistent Strokes: Apply the FastCoat Waterproof in consistent, straight",
    "strokes to achieve an even finish.",
    "6. Drying Time",
    "o Allow the FastCoat Waterproof to dry for 2-4 hours, depending on",
    "environmental conditions such as temperature and humidity.",
    "7. Final Inspection",
    "o Even Coverage: Check the roof to ensure the FastCoat Waterproof has",
    "been applied evenly across the entire surface.",
    "o Touch-ups: Perform any necessary touch-ups with additional FastCoat",
    "Waterproof to cover missed spots or thin areas.",
    "[[PAGE_GAP]]",
    "FastCoat Waterproof as a MidCoat:",
    "Single component, moisture curing polyurethane.",
    "Container Size – 25kg",
    "Coverage Rates (Typical)",
    "1kg / m² (Smooth Surface) – 25m² / 25kg tin",
    "1.5kg / m² (Rough Surface) – 16.6m² / 25kg tin",
    "Allowance should be made for additional coverage rates for embedment of the",
    "Reinforcement Matting at low temperatures.",
    "Typical Drying Times at 15°c",
    "Touch Dry – 3 hours",
    "Minimum Over Coat – 4 hours",
    "Full Cure – 7 days",
    "Storage",
    "FastCoat should be stored between 5°c and 20°c and kept out of the weather elements.",
    "Application Temperatures",
    "FastCoat is based on surface temperature and should be applied between +5°c and the",
    "maximum surface temperature is 35°c.",
    "FastCoat Waterproof as a TopCoat:",
    "[[PAGE_GAP]]",
    "Applying the FastCoat Waterproof is a critical final step in creating a durable and",
    "watertight flat roof.",
    "Steps for Applying FastCoat TopCoat:",
    "1. Safety First – Please see pages 9-10.",
    "2. Inspect the BaseCoat",
    "o Check for Pinholes: Ensure all pinholes have been filled and the surface",
    "is smooth.",
    "o Clean Surface: Make sure the surface is clean and free from dust and",
    "debris. See page 14",
    "3. Reactivation of the Surface (if required)",
    "o If the BaseCoat has been left for more than 14 days, you must reactivate",
    "the surface using MS 2-Part Primer.",
    "o Apply Primer: Apply the MS 2-Part Primer as per LRS instructions and",
    "allow it to dry completely before applying the FastCoat Waterproof.",
    "4. Mixing the FastCoat TopCoat",
    "o Thoroughly mix the FastCoat TopCoat before application. Use a drill",
    "with mixing attachment or mixing stick to ensure uniform consistency.",
    "5. Application of FastCoat TopCoat",
    "o Coverage Rate: Apply the FastCoat TopCoat at a coverage rate of 0.3kg",
    "per m².",
    "o Even Application: Use a short pile roller or brush to apply the FastCoat",
    "TopCoat evenly. Ensure consistent thickness and avoid leaving streaks",
    "or thin spots.",
    "o Consistent Strokes: Apply the FastCoat TopCoat in consistent, straight",
    "strokes to achieve an even finish.",
    "6. Drying Time",
    "o Allow the FastCoat TopCoat to dry for 2-4 hours, depending on",
    "environmental conditions such as temperature and humidity.",
    "7. Final Inspection",
    "o Even Coverage: Check the roof to ensure the FastCoat TopCoat has been",
    "applied evenly across the entire surface.",
    "o Touch-ups: Perform any necessary touch-ups with additional FastCoat",
    "TopCoat to cover missed spots or thin areas.",
    "FastCoat TopCoat:",
    "Single component Polyurethane, Solvent Based Aliphatic Coloured TopCoat.",
    "Container Size – 5.5kg",
    "Coverage Rates (Typical)",
    "[[PAGE_GAP]]",
    "0.3kg / m² (Smooth Surface) – 18.3m² / 5.5kg tin",
    "Typical Drying Times at 15°c",
    "Touch Dry – 3 hours",
    "Minimum Over Coat – 4 hours",
    "Full Cure – 7 days",
    "Storage",
    "FastCoat should be stored between 5°c and 20°c and kept out of the weather elements.",
    "Application Temperatures",
    "FastCoat is based on surface temperature and should be applied between +5°c and the",
    "maximum surface temperature is 35°c.",
    "Completed Roof Surface",
    "Guide to Visual Inspection of the Completed Roof Surface",
    "Objective: Conduct a thorough visual inspection of the completed roof surface to",
    "ensure there are no pinholes, the coverage is even, details are correctly applied at",
    "150mm, and Reinforcement Matting is properly installed over the entire roof area.",
    "Safety Precautions: Please see pages 9-10.",
    "Steps for Visual Inspection:",
    "•   Initial Overview:",
    "o Walk around the perimeter of the roof to get an initial overview of the",
    "surface.",
    "o Take note of any obvious defects or areas that require closer inspection.",
    "•   Check for Pinholes:",
    "o Visual Scan: Perform a visual scan of the entire roof surface. Look closely",
    "for pinholes.",
    "o Detailed Areas: Pay extra attention to seams, edges, and details where",
    "pinholes are more likely to occur.",
    "•   Ensure Even Coverage:",
    "o Uniform Thickness: Verify that the FastCoat Waterproof is consistent across",
    "the entire roof. There should be no thin spots or exposed substrate.",
    "[[PAGE_GAP]]",
    "o  Edges and Corners: Check edges, corners, and transitions to ensure they are",
    "fully coated and have no exposed areas.",
    "o Colour Consistency: Look for colour consistency across the surface, as",
    "variations can indicate uneven application.",
    "•   Inspect Details at 150mm:",
    "o Measure Height: Use a measuring tape to check that details such as",
    "terminations, upstands, and other critical points are coated to a minimum",
    "height of 150mm where possible.",
    "o Detail Work: Ensure all details are properly sealed and the FastCoat",
    "Waterproof is applied consistently at the required height.",
    "•   Verify Reinforcement Matting:",
    "o Visible Matting: Inspect areas where Reinforcement Matting was applied.",
    "The Reinforcement Matting should be fully embedded in the coating with",
    "no exposed edges.",
    "o Coverage: Ensure the Reinforcement Matting extends to cover all critical",
    "areas, such as joints, seams, and around roof penetrations.",
    "o Bonding: Check that the Reinforcement Matting is well-bonded to the",
    "substrate and there are no air pockets or wrinkles.",
    "•   Final Checks:",
    "o Seams and Joints: Verify that all seams and joints are fully sealed and there",
    "are no gaps or openings.",
    "o Overall Condition: Assess the overall condition of the roof surface. Ensure it",
    "looks uniform and well-maintained.",
    "•   Document Findings:",
    "o Photographic Evidence: Take photos of the roof surface, especially any",
    "areas of concern or interest. Capture before and after images if any touch-",
    "up work is required.",
    "o Detailed Notes: Write detailed notes on your findings, including any defects,",
    "areas that need additional work, and the overall condition of the roof.",
    "Addressing Issues:",
    "•   Pinholes: Mark any pinholes with chalk or tape. Prepare a small amount of LRS",
    "PU Mastic to fill in the pinholes before reapplying FastCoat Waterproof.",
    "•   Uneven Coverage: Apply additional FastCoat Waterproof to any areas with",
    "insufficient coverage to achieve uniform thickness.",
    "•   Detail Adjustments: Correct any issues with details that are not at the required",
    "150mm height where possible. Apply additional coating if necessary.",
    "•   Reinforcement Matting: Ensure any improperly applied Reinforcement",
    "Matting is corrected by applying additional FastCoat Waterproof and",
    "embedding new Reinforcement Matting as needed.",
    "[[TRAFFIC_START]]",
    "Traffic Coat Previsions for walkways, maintenance routes etc.:",
    "[[PAGE_GAP]]",
    "Once the LRS FastCoat Waterproof has fully cured, Traffic Coat can be applied.",
    "LRS Traffic Coat is applied in 2 coats (Holding Layer & Seal Coat) and typically",
    "cures in 30 mins.",
    "Holding Layer is applied @ 0.2kg m² and while Traffic Coat is still wet",
    "immediately broadcast to saturation, completely blinding the surface with 3kg",
    "m² of Emery Aggregate.",
    "Once the Base Layer has fully cured, typically in 30 minutes, the contractor will",
    "need to brush and bag up all the loose aggregate before applying the Seal Coat.",
    "Seal Coat is applied at 0.2kg m² ensuring the aggregate is encapsulated.",
    "Ensure all masking tape is removed once the walkway is complete and the Seal",
    "Coat is still wet to leave a crisp edge.",
    "[[TRAFFIC_END]]",
    "TAKE IMAGES OF EACH STEP OF THE ABOVE IF APPLYING FOR A PRODUCT",
    "GUARANTEE",
    "General Guidance and Requirements",
    "Drying Out – Equipment:",
    "These are readily available commercially from local tool plant hire companies.",
    "Leaf Blowers",
    "Hot Air Blower",
    "Roof Pumps",
    "Defects:",
    "This specification provided by LRS is written on the basis that the substrates, roof",
    "deck and structures are sound and suitable. We cannot accept responsibility for the",
    "consequences of defects in the roof deck or structure.",
    "Installation:",
    "All LRS Waterproofing Systems are to be installed in accordance with this",
    "specification.",
    "Building Works:",
    "[[PAGE_GAP]]",
    "It is the contractor’s responsibility to ensure suitable protection of semi-completed or",
    "completed works.",
    "Protection of Works:",
    "It is the contractor’s responsibility to ensure any relating plant, equipment or",
    "materials being stored or placed onto the waterproofing membrane are sufficiently",
    "protected.",
    "Delays:",
    "All or general areas: Overcoating must be carried out within 14 days of the",
    "application of the preceding coat (Primer or Waterproofing).",
    "Coatings that are over 14 days will need to be re-activated using LRS MS 2-Part Primer",
    "at a coverage of 0.2kg per m².",
    "General Guidance - requirements",
    "Prepared Surfaces – Requirement:",
    "Prepared surfaces and substrates to receive the new FastCoat Pro Waterproofing",
    "Membrane must be prepared all in accordance with this specification and must be",
    "clean from all dirt, dust and loose materials. In addition, all surfaces must be dry",
    "before application.",
    "Storage:",
    "All LRS materials must always be stored indoors between 5°c and 20°c.",
    "Note: Coverage rates are adversely affected by high and low application temperatures.",
    "Safe Working:",
    "[[PAGE_GAP]]",
    "All works are to be carried out in accordance with the current Health and Safety",
    "Legislation. Please see pages 9-10.",
    "Inclement Weather Protection:",
    "If rain is due no LRS Waterproofing coatings should be laid.",
    "The contractor must ensure at the end of each day that any exposed membranes or",
    "substrates that are susceptible to damage through water ingress are sealed and",
    "protected to ensure complete water tightness.",
    "[[PAGE_GAP]]",
    "Maintenance After Installation",
    "The new roof coverings should be managed in accordance with the recommendations",
    "of BS6229:2003 with regards to ongoing maintenance.",
    "They should be routinely inspected and cleared of any debris every spring and",
    "autumn. This will need to be undertaken more often if the roof is surrounded by",
    "trees etc.",
    "Please note that failure to follow maintenance guidelines can invalidate the product",
    "guarantee.",
    "Guarantee – Materials Only",
    "Materials only. The following guarantee specification is covered by LRS product",
    "guarantee for the period of 25-years from the date of practical completion.",
    "Please Note: Only Waterproofing products supplied by LRS will be covered in this",
    "guarantee."
  ];
  
  export const TWENTY_YEAR_PRIMER = [
    "MS 2-Part Primer:",
    "Priming the roof surface using MS 2-Part Primer is essential for ensuring proper adhesion of the",
    "FastCoat Waterproof coating, especially on various surfaces like metal, single-ply, GRP, glass, plastic,",
    "concrete, brickwork, fibre cement, and existing coatings.",
    "Steps to Prime the Surface:",
    "1. Safety First – Please see pages 9-10.",
    "1. Surface Preparation",
    "• Ensure the surface is clean, dry, and free from dust, debris, and grease.",
    "• Follow the cleaning steps outlined previously if necessary. Please see page 12.",
    "2. Measure the Area",
    "• Measure the total area to be primed to ensure you mix the correct amount of MS 2-",
    "Part Primer.",
    "• Remember that 12.5kg tin of MS 2-Part Primer covers 62.5m².",
    "3. Mix the MS 2-Part Primer",
    "• MS 2-Part Primer requires thorough mixing of its 2 components.",
    "[[PAGE_GAP]]",
    "• Mix Part A with Part B, If part mixing then the mixing ratio would be 4:1 mix.",
    "• Use a drill with mixing attachment or mixing stick for thorough mixing.",
    "4.   Apply the Primer",
    "• Use a short pile roller to apply the MS 2-Part Primer evenly on the surface.",
    "• Roll the MS 2-Part Primer in straight, even strokes to ensure uniform coverage.",
    "• Pay attention to corners, edges, and seams to ensure they are adequately coated.",
    "5.   Maintain Coverage Rate",
    "• Ensure you apply the MS 2-Part Primer at the recommended coverage rate of 0.2kg",
    "per m².",
    "• A 12.5kg tin should cover 62.5m², so adjust the amount of MS 2-Part Primer used",
    "based on the area being covered.",
    "6.   Drying Time",
    "• Allow the MS 2-Part Primer to dry, typically 4-6 hours before applying the FastCoat",
    "Waterproof coating.",
    "• Drying times can vary based on environmental conditions like temperature and",
    "humidity.",
    "7.   Clean Up",
    "• Clean tools and equipment.",
    "• Dispose of any leftover primer and containers according to local regulations."
  ];
  
  export const TWENTY_FIVE_YEAR_PRIMER = [
    "MS 2-Part Primer:",
    "Priming the roof surface using MS 2-Part Primer is essential for ensuring proper",
    "adhesion of the FastCoat Waterproof coating, especially on various surfaces like",
    "metal, single-ply, GRP, glass, plastic, concrete, brickwork, fibre cement, and existing",
    "coatings.",
    "Steps to Prime the Surface:",
    "1. Safety First – Please see pages 9-10.",
    "1. Surface Preparation",
    "• Ensure the surface is clean, dry, and free from dust, debris, and grease.",
    "• Follow the cleaning steps outlined previously if necessary. Please see",
    "page 12.",
    "2. Measure the Area",
    "• Measure the total area to be primed to ensure you mix the correct",
    "amount of MS 2-Part Primer.",
    "• Remember that 12.5kg tin of MS 2-Part Primer covers 62.5m².",
    "3. Mix the MS 2-Part Primer",
    "• MS 2-Part Primer requires thorough mixing of its 2 components.",
    "• Mix Part A with Part B, If part mixing then the mixing ratio would be 4:1",
    "mix.",
    "• Use a drill with mixing attachment or mixing stick for thorough mixing.",
    "4. Apply the Primer",
    "• Use a short pile roller to apply the MS 2-Part Primer evenly on the",
    "surface.",
    "• Roll the MS 2-Part Primer in straight, even strokes to ensure uniform",
    "coverage.",
    "• Pay attention to corners, edges, and seams to ensure they are",
    "adequately coated.",
    "5. Maintain Coverage Rate",
    "• Ensure you apply the MS 2-Part Primer at the recommended coverage",
    "rate of 0.2kg per m².",
    "• A 12.5kg tin should cover 62.5m², so adjust the amount of MS 2-Part",
    "Primer used based on the area being covered.",
    "6. Drying Time",
    "• Allow the MS 2-Part Primer to dry, typically 4-6 hours before applying",
    "the FastCoat Waterproof coating.",
    "• Drying times can vary based on environmental conditions like",
    "temperature and humidity.",
    "[[PAGE_GAP]]",
    "7. Clean Up",
    "• Clean tools and equipment.",
    "• Dispose of any leftover primer and containers according to local",
    "regulations."
  ];
  